"""

Revision ID: 87c649b7a8ef
Revises: a1f963eda280
Create Date: 2024-09-04 08:20:25.696520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c649b7a8ef'
down_revision: Union[str, None] = 'a1f963eda280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_attributes', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_attributes', 'hashed_password')
    # ### end Alembic commands ###
