version: '3.8'

services:
  api:
    build: .
    container_name: "api"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: 'mysql/mysql-server:8.0'
    restart: always
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: